name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore ./api/api.csproj

    - name: Build
      run: dotnet build --no-restore ./api/api.csproj -c Release

    - name: Publish
      run: dotnet publish --no-build ./api/api.csproj -c Release -o ./api/out

    - name: Build and Push Docker Image
      uses: mr-smithers-excellent/docker-build-push@v4
      with:
        image: wombir/finshark-api
        registry: docker.io
        dockerfile: ./api/Dockerfile
        directory: ./api
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
