# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build and Push Docker Image to GCP
      uses: mr-smithers-excellent/docker-build-push@v6
      with:
        image: finshark/finsharp-app
        registry: gcr.io
        dockerfile: ./frontend/Dockerfile
        directory: ./frontend
        username: _json_key
        password: ${{ secrets.GCP_SA_KEY }}